[book]
authors = ["erhant"]
language = "en"
multilingual = false
src = "src"
title = "Circom101"

# uses KaTeX instead of MathJax, much better interop
[preprocessor.katex]
after = ["links"]

# converts mermaid drawings to SVG
[preprocessor.mermaid]
command = "mdbook-mermaid"

# generate table of contents
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output]

[output.html]
additional-css = ["./utils/custom.css"]
additional-js = ["./utils/mermaid.min.js", "./utils/mermaid-init.js"]
git-repository-url = "https://github.com/erhant/circom101"
git-repository-icon = "fa-github"
default-theme = "rust"
preferred-dark-theme = "navy"